variables:
  STACK: "clean"
  API_PROJECT_NAME: "Wally.CleanArchitecture.WebApi"
  #
  VERSION: "0.1.${CI_PIPELINE_ID}"
  #CI_DEBUG_TRACE: "true"

stages:
  - build
  - test
  - publish
  - deploy

build:sln:
  extends:
    - .build:dotnet

test:sln:
  extends:
    - .test:dotnet
  needs:
    - build:sln

include:
  - project: wally/wally.common.pipelines
    ref: master
    file:
      - /src/gitlab-ci.yml
