variables:
  SLN1_SOLUTION_NAME: "Wally.CleanArchitecture.ApiGateway"
  SLN2_SOLUTION_NAME: "Wally.CleanArchitecture.MicroService"
  TPL_PROJECT_NAME: "Wally.CleanArchitecture.Template"
  #
  VERSION: "1.2.${CI_PIPELINE_ID}"
  #CI_DEBUG_TRACE: "true"

stages:
  - build
  - test
  - publish
  - deploy

build:sln1:
  extends:
    - .build:dotnet
  variables:
    SOLUTION_NAME: ${SLN1_SOLUTION_NAME}

build:sln2:
  extends:
    - .build:dotnet
  variables:
    SOLUTION_NAME: ${SLN2_SOLUTION_NAME}

build:tpl:
  extends:
    - .build:dotnet
  variables:
    SOLUTION_NAME: ${TPL_PROJECT_NAME}

test:sln1:
  extends:
    - .test:dotnet
  needs:
    - build:sln1
  variables:
    SOLUTION_NAME: ${SLN1_SOLUTION_NAME}

test:sln2:
  extends:
    - .test:dotnet
  needs:
    - build:sln2
  variables:
    SOLUTION_NAME: ${SLN2_SOLUTION_NAME}

publish:tpl:
  extends:
    - .publish:nuget
  needs:
    - test:sln1
    - test:sln2
  variables:
    PROJECT_NAME: ${TPL_PROJECT_NAME}

deploy:nuget:tpl:
  extends:
    - .deploy:nuget
  needs:
    - publish:tpl
  variables:
    PROJECT_NAME: ${TPL_PROJECT_NAME}

deploy:baget:tpl:
  extends:
    - .deploy:baget
  needs:
    - publish:tpl
  variables:
    PROJECT_NAME: ${TPL_PROJECT_NAME}

include:
  - project: wally/wally.common.pipelines
    ref: master
    file:
      - /src/gitlab-ci.yml
