variables:
  TPL_PROJECT_NAME: "Wally.CleanArchitecture.Template"
  #
  VERSION: "0.1.${CI_PIPELINE_ID}"
  #CI_DEBUG_TRACE: "true"

stages:
  - build
  - test
  - publish
  - deploy

build:sln:
  extends:
    - .build:dotnet

test:sln:
  extends:
    - .test:dotnet
  needs:
    - build:sln

publish:tpl:
  extends:
    - .publish:nuget
  needs:
    - test:sln
  variables:
    PROJECT_NAME: ${TPL_PROJECT_NAME}

deploy:tpl:
  extends:
    - .deploy:nuget
  needs:
    - publish:tpl
  variables:
    PROJECT_NAME: ${TPL_PROJECT_NAME}

include:
  - project: wally/wally.common.pipelines
    ref: master
    file:
      - /src/gitlab-ci.yml
