variables:
  SLN1_SOLUTION_NAME: "Wally.CleanArchitecture.ApiGateway"
  SLN2_SOLUTION_NAME: "Wally.CleanArchitecture.MicroService"
  TPL_PROJECT_NAME: "Wally.CleanArchitecture.Template"
  NPM_PROJECT_NAME: "Wally.CleanArchitecture.MicroService.Application.Contracts"
  #
  VERSION: "1.3.${CI_PIPELINE_ID}"
  #CI_DEBUG_TRACE: "true"

stages:
  - build
  - test
  - publish
  - deploy

build:sln1:
  extends:
    - .build:dotnet
  variables:
    SOLUTION_NAME: ${SLN1_SOLUTION_NAME}

build:sln2:
  extends:
    - .build:dotnet
  variables:
    SOLUTION_NAME: ${SLN2_SOLUTION_NAME}

build:tpl:
  extends:
    - .build:dotnet
  variables:
    SOLUTION_NAME: ${TPL_PROJECT_NAME}

test:sln1:
  extends:
    - .test:dotnet
  needs:
    - build:sln1
  variables:
    SOLUTION_NAME: ${SLN1_SOLUTION_NAME}

test:sln2:
  extends:
    - .test:dotnet
  needs:
    - build:sln2
  variables:
    SOLUTION_NAME: ${SLN2_SOLUTION_NAME}

test:npm:
  extends:
    - .test:node
  needs:
    - build:sln2
  variables:
    PROJECT_NAME: Wally.CleanArchitecture.MicroService/${NPM_PROJECT_NAME}/generated
  allow_failure: true

publish:tpl:
  extends:
    - .publish:nuget
  needs:
    - test:sln1
    - test:sln2
  variables:
    PROJECT_NAME: ${TPL_PROJECT_NAME}

deploy:nuget:tpl:
  extends:
    - .deploy:nuget
  needs:
    - publish:tpl
  variables:
    PROJECT_NAME: ${TPL_PROJECT_NAME}
  environment:
    name: ${ENV}_${TPL_PROJECT_NAME}
    url: https://www.nuget.org/packages/${TPL_PROJECT_NAME}/${VERSION}

deploy:baget:tpl:
  extends:
    - .deploy:baget
  needs:
    #- publish:tpl
    - test:sln1
    - test:sln2
  variables:
    PROJECT_NAME: ${TPL_PROJECT_NAME}

deploy:node:npm:
  extends:
    - .deploy:node
  needs:
    - test:npm
  variables:
    PROJECT_NAME: Wally.CleanArchitecture.MicroService/${NPM_PROJECT_NAME}/generated
  environment:
    name: ${ENV}_${NPM_PROJECT_NAME}
    url: https://www.npmjs.com/package/${NPM_PROJECT_NAME}/v/${VERSION}

include:
  - project: wally/wally.common.pipelines
    ref: master
    file:
      - /src/gitlab-ci.yml
