apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  namespace: wally
  name: wally-cleanarchitecture
  description: The dotnet template
  labels:
    example.com/custom: custom_label_value
  annotations:
    backstage.io/techdocs-ref: value
    backstage.io/source-location: url:https://git.wally.best/wally/Wally.CleanArchitecture/-/blob/master/
    example.com/service-discovery: artistweb
    circleci.com/project-slug: github/example-org/artist-website
  tags:
    - dotnet
  links:
    - url: https://www.nuget.org/packages/Wally.CleanArchitecture.Template/
      title: NuGet
      icon: dashboard
      type: admin-dashboard
spec:
  type: package
  lifecycle: production
  owner: wally
  system: public-packages
