version: '3.9'

services:
    api:
        # http://localhost:5000
        # https://localhost:5001
        # http://localhost:5000/healthchecks
        # http://localhost:5000/healthchecks-UI
        # http://localhost:5000/healthchecks-api
        # http://localhost:5000/healthchecks-api/ui-settings
        image: wally.cleanarchitecture.apigateway.webapi
        container_name: api
        restart: "no"
        ports:
            - "5000:5000"
            - "5001:5001"
        build:
            context: ./Wally.CleanArchitecture.ApiGateway/Wally.CleanArchitecture.ApiGateway.WebApi
            dockerfile: Dockerfile.development
        environment:
            TZ: ${TZ}
            DOTNET_DASHBOARD_OTLP_ENDPOINT_URL: http://aspire:18889
            OTEL_EXPORTER_OTLP_ENDPOINT: http://aspire:18889
            #
            HealthChecksUI__HealthChecks__0__Uri: http://api/healthChecks
            # ...
        volumes:
            - ./Wally.CleanArchitecture.ApiGateway/Wally.CleanArchitecture.ApiGateway.WebApi/bin/Debug/net8.0:/app

    aspire:
        # http://localhost:18888
        # http://localhost:18889
        image: mcr.microsoft.com/dotnet/nightly/aspire-dashboard:latest
        container_name: aspire
        restart: "no"
        ports:
            - "18888:18888"
            - "18889:18889"
        environment:
            TZ: ${TZ}
            DASHBOARD__FRONTEND__BROWSERTOKEN: ${DASHBOARD__OTLP__PRIMARYAPIKEY} # Dashboard:Frontend:BrowserToken
            # DASHBOARD__OTLP__AUTHMODE: ApiKey
            # DASHBOARD__OTLP__PRIMARYAPIKEY: ${DASHBOARD__OTLP__PRIMARYAPIKEY}

networks:
    default:
        external: false
        name: "Wally.CleanArchitecture"
