@host = http://localhost:5181

GET {{host}}/Users
Accept: application/json

###

GET {{host}}/Users/{{$random.uuid}}
Accept: application/json

###

GET {{host}}/Users?$orderby=Name&$skip=1&$top=2
Accept: application/json

###

#### Tests
#
#curl -X GET "https://localhost:7197/Users/3fa85f64-5717-4562-b3fc-2c963f66afa6" -H "accept:
#application/json;odata.metadata=minimal;odata.streaming=true"  
#curl -X GET "https://localhost:7197/Users" -H "accept: application/json;odata.metadata=minimal;odata.streaming=true"  
#curl -X GET "https://localhost:7197/Users?$orderby=Id&$top=1" -H "accept:
#application/json;odata.metadata=minimal;odata.streaming=true"  
#curl -X GET "https://localhost:7197/Users?$count=true&$orderby=Id&$top=0" -H "accept:
#application/json;odata.metadata=minimal;odata.streaming=true"  
#curl -X GET "https://localhost:7197/Users?$count=true&$orderby=Id&$skip=2&$top=2" -H "accept:
#application/json;odata.metadata=minimal;odata.streaming=true"
#
#```json
#{
#	"items":[
#		{"id":"3fa85f64-5717-4562-b3fc-2c963f66afa8","name":"testDbData3"}
#	],
#	"pageInfo":{
#		"index":1,
#		"size":2,
#		"totalItems":3
#	}
#}
#```
#
#curl -X GET "https://localhost:7197/Users?$orderby=Name%20desc&$top=3" -H "accept:
#application/json;odata.metadata=minimal;odata.streaming=true"
#
#```json
#{
#	"items":[
#		{"id":"3fa85f64-5717-4562-b3fc-2c963f66afa8","name":"testDbData3"},
#		{"id":"3fa85f64-5717-4562-b3fc-2c963f66afa7","name":"testDbData2"},
#		{"id":"3fa85f64-5717-4562-b3fc-2c963f66afa6","name":"testDbData1"}
#	],
#	"pageInfo":{
#		"index":0,
#		"size":3,
#		"totalItems":3
#	}
#}
#```
