@host = http://localhost:5181

GET {{host}}/Users
Accept: application/json

###

GET {{host}}/Users/{{$random.uuid}}
Accept: application/json

###

GET {{host}}/Users?$orderby=Name&$skip=1&$top=2
Accept: application/json

###