# @name getUsers
GET {{host}}/Users
Accept: application/json

###

# @name getUser
GET {{host}}/Users/{{$random.uuid}}
Accept: application/json

###

# @name getUser
GET {{host}}/Users?$orderby=Name&$skip=1&$top=2
Accept: application/json

###

# @name getUser
GET {{host}}/Users?$filter=Id eq ({{$random.uuid}})
Accept: application/json

###

# @name getUser
GET {{host}}/Users?$filter=Name eq 'test'
Accept: application/json

###

# @name postUser
POST {{host}}/Users
Accept: application/json
Content-Type: application/json

{
    "name": "test"
}

###

# @name deleteUser
DELETE {{host}}/Users/1996dfbd-e33f-4623-96f4-0080b5f7f57f
Accept: application/json

###
